local utils = require("manuscript.utils")
local stub = require("luassert.stub")

describe("utils", function()
  describe("get_current_directory", function()
    it("should return the last segment of the nested path", function()
      stub(vim.fn, "getcwd", "/home/bakabruh/personal/claw-code/")
      assert.equals("claw-code", utils.get_current_directory())
    end)
  end)
end)
